marton_topcars_default:
    pattern:  /
    defaults: { _controller: MartonTopCarsBundle:Page:home }

marton_topcars_game:
    path:     /game
    defaults: { _controller: MartonTopCarsBundle:Page:game }

# Car
marton_topcars_garage:
    path: /garage
    defaults: {_controller: MartonTopCarsBundle:Car:garage }

marton_topcars_dealership:
    path: /dealership/{option}
    defaults: {_controller: MartonTopCarsBundle:Car:dealership, option: "available" }
    requirements:
        option:  available|all

# User
marton_topcars_leaderboard:
    path: /leaderboard
    defaults: { _controller: MartonTopCarsBundle:User:leaderboard }

marton_topcars_user:
    path: /user/{user}
    defaults: {_controller: MartonTopCarsBundle:User:profile }

# SuggestedCar
marton_topcars_pending:
    path: /pending
    defaults: {_controller: MartonTopCarsBundle:SuggestedCar:pending }

marton_topcars_create_suggestedCar:
    path: /suggest/create
    defaults: {_controller: MartonTopCarsBundle:SuggestedCar:create }

marton_topcars_pending_vote:
    path:  /pending/vote
    defaults: { _controller: MartonTopCarsBundle:SuggestedCar:vote }

marton_topcars_pending_accept:
    path:  /pending/accept
    defaults: { _controller: MartonTopCarsBundle:SuggestedCar:accept }

marton_topcars_pending_edit_or_create:
    path:  /pending/edit
    defaults: { _controller: MartonTopCarsBundle:SuggestedCar:editOrCreate }

marton_topcars_pending_query:
    path: /pending/query
    defaults: { _controller: MartonTopCarsBundle:SuggestedCar:query }

# Account
marton_topcars_register:
    path:     /register
    defaults: { _controller: MartonTopCarsBundle:Account:register }

marton_topcars_create_account:
    path:     /register/create
    defaults: { _controller: MartonTopCarsBundle:Account:create }

# Users should be automatically redirected when they have to login
marton_topcars_login:
    path:     /login
    defaults: { _controller: MartonTopCarsBundle:Account:login }

marton_topcars_login_check:
    path: /login_check

marton_topcars_logout:
    path: /logout

marton_topcars_admin_execute:
    path: /admin/execute
    defaults: { _controller: MartonTopCarsBundle:Data:addPricesToCars }

# Ajax requests
marton_topcars_post_score:
    path:  /ajax/post_score
    defaults: { _controller: MartonTopCarsBundle:Ajax:postUserScore }

# trailing slash should always be removed from the end of the URL
remove_trailing_slash:
    path: /{url}
    defaults: { _controller: MartonTopCarsBundle:Redirect:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]