marton_topcars_default:
    pattern:  /
    defaults: { _controller: MartonTopCarsBundle:Page:home }

# Account

marton_topcars_register:
    path:     /register
    defaults: { _controller: MartonTopCarsBundle:Account:register }

marton_topcars_create_account:
    path:     /register/create
    defaults: { _controller: MartonTopCarsBundle:Account:create }

# Users should be automatically redirected when they have to login
marton_topcars_login:
    path:     /login
    defaults: { _controller: MartonTopCarsBundle:Account:login }

marton_topcars_login_check:
    path: /login_check

marton_topcars_logout:
    path: /logout

# trailing slash should always be removed from the end of the URL
remove_trailing_slash:
    path: /{url}
    defaults: { _controller: MartonTopCarsBundle:Redirect:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]